<?php

/**
 * Implements hook_menu().
 */
function annotator_menu() {
  $items = array();
  
  $items['annotator/bullet-point-attachment'] = array(
    'title' => 'Bilag',
    'type' => MENU_CALLBACK,
    'page callback' => '_annotator_view',
    'access arguments' => array('access content')
  );
  
  $items['annotator/bullet-point-attachment/print'] = array(
    'title' => 'Bilag Print Version',
    'type' => MENU_CALLBACK,
    'page callback' => '_annotator_view_print',
    'access arguments' => array('access content')
  );


  return $items;
}

function _annotator_view($bilag_id = '') {
	$text = 'Intet bilag er fundet';
  
	if (!empty($bilag_id)){
	  $bilag = node_load($bilag_id);
	  if (strcmp($bilag->type, 'bullet_point_attachment') == 0){
	    //drupal_add_js(drupal_get_path('module', 'annotator') . '/lib/jquery.min.js');
	    drupal_add_js(drupal_get_path('module', 'annotator') . '/lib/annotator-full.min.js');
	    drupal_add_js(drupal_get_path('module', 'annotator') . '/lib/touch-plugin/annotator.touch.min.js');
	    drupal_add_js(drupal_get_path('module', 'annotator') . '/lib/json2.js');
    
	    drupal_add_js(drupal_get_path('module', 'annotator') . '/annotator.js');
	    
	    global $user;
	    drupal_add_js('init("'.$user->name.'","'.$bilag_id.'");', 'inline');
    
	    drupal_add_css(drupal_get_path('module', 'annotator') . '/lib/touch-plugin/annotator.touch.css');
	    drupal_add_css(drupal_get_path('module', 'annotator') . '/lib/annotator-full.min.css');
	  
	    drupal_set_title('Bilag - '.$bilag->title);
	    $text = $bilag->field_bpa_body['und'][0]['value'];
	  }
	}
	$link = $GLOBALS['base_path'].'?q=/print/annotator/bullet-point-attachment/print/'.$bilag_id;
	
	return ('<div class="node">
		<div class="help-button" title="Help text goes here"></div>
		<div align="right"><input class="form-submit" type="button" onclick="window.open(\''.$link.'\')" value="Print"></div>'.
		'<div id="content">'.$text.'</div>
		</div>');
}

function _annotator_view_print($bilag_id = '') {
	$text = 'Intet bilag er fundet';
  
	if (!empty($bilag_id)){
	  $bilag = node_load($bilag_id);
	  if (strcmp($bilag->type, 'bullet_point_attachment') == 0){
	    
	    drupal_set_title('Bilag - '.$bilag->title);
	    $header = '<h3>Bilag - '.$bilag->title.'</h3>';
	    
	    $body = $bilag->field_bpa_body['und'][0]['value'];
	    
	    //getting annotations from storage
	    $annotations = _annotator_curl_annotations($bilag_id);
	    
	    //initiating variabes
	    $annotation_list = '';
	    $note_nr = 1;
	    
	    //printing annotations one by one in right order
	    while (!empty($annotations)){
	      //flushing array indexing
	      $annotations = array_values($annotations);
	      
	      $first_note_ind = 0;
	      for ($i=1; $i < count($annotations); $i++){
		if ($annotations[$i]['ranges'][0]['startOffset'] < $annotations[$first_note_ind]['ranges'][0]['startOffset'])
		  $first_note_ind = $i;
	      }
	      $body = _annotator_append_index($body, $annotations[$first_note_ind], $note_nr);
	      $annotation_list .= _annotator_append_note($annotations[$first_note_ind], $note_nr);
	      $note_nr++;
	      
	      unset($annotations[$first_note_ind]);
	    }
	    
	    $text = $header;
	    $text .= $body;
	    $text .= "<hr/>";
	    $text .= $annotation_list;
	  }
	}
	
	return ('<div class="node" id="content">'.$text.'</div>');
}

function _annotator_curl_annotations($bilag_id){
  //globals
  $IP_ADDRESS = '192.168.42.179';
  $PORT_NR = '5000';

  global $user;
  $url = $IP_ADDRESS.':'.$PORT_NR.'/search?drupal_user='.$user->name.'&bilag_id='.$bilag_id;
  
  $ch = curl_init();

  // Set query data here with the URL
  curl_setopt($ch, CURLOPT_URL, $url); 

  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_TIMEOUT, '3');
  $content_json = trim(curl_exec($ch));
  curl_close($ch);
  
  $content = json_decode($content_json, true);
  return $content['rows'];
}

function _annotator_append_index($body, $note, $note_nr){
  $positionStart = strpos($body, $note['quote'], $note['ranges'][0]['startOffset']);
  $positionEnd = $positionStart+strlen($note['quote']);
  $body = substr_replace($body, '<sup><b>['.$note_nr.']</b></sup>', $positionEnd, 0);
  
  return $body;
}

function _annotator_append_note($note, $index){
  return '<b>['.$index.']</b> '.$note['text'].'<br/>';
}


?>

