<?php


function mymodule_menu(){
  $items = array();

	//Test items
	$items['mymodule/test/pager'] = array(
   	  'title' => 'Drupal 7 test pager',
	  'type' => MENU_CALLBACK,
	  'page callback' => 'mymodule_test_pager',
	  'access arguments' => array('access content')
	); 	 
	  
	$items['mymodule/test/pager/callback'] = array(
	  'title' => 'Test Pager Callback',
	  'type' => MENU_CALLBACK,
	  'page callback' => '_mymodule_test_pager_callback',
	  'access arguments' => array('access content'),
	);

	  return $items;
}

function mymodule_enable() {
	//Make user goto the test pager page.
	$link = l('Test Pager', 'mymodule/test/pager');
	drupal_set_message("Please visit $link to see Ajaxed paging in action.");
}

function mymodule_test_pager () {

	drupal_add_js(drupal_get_path('module', 'mymodule') . '/jquery.url.js');
	drupal_add_js(drupal_get_path('module', 'mymodule') . '/mymodule.js');
	drupal_add_js('initializeTable();', 'inline');
			
	return ('<div id="table-container"></div>');
}

function _mymodule_test_pager_callback () {
	header("Content-type: text/html");
	header("Expires: Wed, 29 Jan 1975 04:15:00 GMT");
	header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
	header("Cache-Control: no-cache, must-revalidate");
	header("Pragma: no-cache");
	
	//Create a list of headers for your Html table (see Drupal 7 docs for theme_table here: http://api.drupal.org/api/drupal/includes--theme.inc/function/theme_table/7
	$header = array(
		array('data' => 'Title', 'field' => 'title', 'sort' => 'asc'),
		array('data' => 'Node ID', 'field' => 'nid'),
		array('data' => 'Type', 'field' => 'type'),
		array('data' => 'Created', 'field' => 'created'),
		array('data' => 'Published'),
		);

	//Create the Sql query. This uses various parts of Drupal 7's new DBTNG database abstraction layer. See these links for details:
	//Dynamic queries: http://drupal.org/node/310075
	//Extenders: http://drupal.org/node/508796
	//Table sort: http://drupal.org/node/310075#table_sort
	
	$query = db_select('node', 'n')
				->condition('status', 1)	//Only published nodes, change condition as it suits you
				->extend('PagerDefault') 	//Pager Extender
					->limit(10)				//10 results per page
				->extend('TableSort')		//Sorting Extender
					->orderByHeader($header)//Field to sort on is picked from $header
				->fields ('n', array (
					'nid',
					'title',
					'type',
					'created',
					'status',
				));
	
	$results = $query
				->execute();
	
	$rows = array();	
	foreach ($results as $node) {
		$rows[] = array(
					'data' => array(
						  l($node->title, 'node/'. $node->nid),
						  $node->nid,
						  $node->type,
						  format_date($node->created),
						  $node->status
					)
		);
	}
	
	//Theme the html table: http://api.drupal.org/api/drupal/includes--theme.inc/function/theme_table/7
	$html = theme('table', 
				array(
					'header' => $header,
					'rows'=>$rows,
					'caption' => 'Creating Drupal 7 Ajaxed tables',	//Optional Caption for the table
					'sticky' => TRUE,						//Optional to indicate whether the table headers should be sticky
					'empty' => 'No nodes created...',		//Optional empty text for the table if resultset is empty
				)
			);
	
	//Append pager: http://api.drupal.org/api/drupal/includes--pager.inc/function/theme_pager
	$html .= theme('pager',
				array(
					'tags' => array()
				)
			);
			
	die ($html);
}
